//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sim_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STYLE_WEIGHT
    {
        public int ID { get; set; }
        public string Style { get; set; }
        public Nullable<double> Vis { get; set; }
        public Nullable<double> Ver { get; set; }
        public Nullable<double> Act { get; set; }
        public Nullable<double> Ref { get; set; }
        public Nullable<double> Seg { get; set; }
        public Nullable<double> Glo { get; set; }
        public Nullable<double> Sen { get; set; }
        public Nullable<double> Int { get; set; }
        public Nullable<double> Bloom1 { get; set; }
        public Nullable<double> Bloom2 { get; set; }
        public Nullable<double> Bloom3 { get; set; }
        public Nullable<double> Bloom4 { get; set; }
        public Nullable<double> Bloom5 { get; set; }
        public Nullable<double> Bloom6 { get; set; }
        public Nullable<double> Interesting { get; set; }
        public Nullable<double> NotInteresting { get; set; }
    }
}
