//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sim_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBJECT
    {
        public string SubjectID { get; set; }
        public string SubjectName { get; set; }
    }
}
