//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sim_frontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Right { get; set; }
        public Nullable<int> Act { get; set; }
        public Nullable<int> Ref { get; set; }
        public Nullable<int> Sen { get; set; }
        public Nullable<int> Int { get; set; }
        public Nullable<int> Vis { get; set; }
        public Nullable<int> Ver { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<int> Glo { get; set; }
    }
}
